#!/bin/sh

### Set new dotfiles

#ln -sf $PWD/.zshrc ~/.zshrc
ln -sf $PWD/.bash_prompt ~/.bash_prompt
ln -sf $PWD/.aliases ~/.aliases
ln -sf $PWD/.profile ~/.profile
ln -sf $PWD/Brewfile ~/Brewfile

### Show hidden files in finder

defaults write com.apple.finder AppleShowAllFiles TRUE

### Update brew

ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"

sh brewinit


# XCode Command Line Tools
if [ $(xcode-select -p &> /dev/null; printf $?) -ne 0 ]; then
	xcode-select --install &> /dev/null

	# Wait until the XCode Command Line Tools are installed
	while [ $(xcode-select -p &> /dev/null; printf $?) -ne 0 ]; do
	    sleep 5
	done
fi

print_success "XCode Command Line Tools"
printf "\n"

#chsh -s $(which zsh) $USER


#### Setup git-stuff

git config --global color.ui true
git config --global user.name "Nils Neumann"
git config --global user.email mail@der-zyklop.de
git config --global format.pretty oneline
git config --global push.default simple

# For more usefull git-stuff see <http://git-scm.com/book/en/Customizing-Git-Git-Configuration>

### Sass & Compass

sudo gem install compass --version 0.12.4

### Grunt

brew install node
npm install -g grunt-cli

### Fonts
cp -r submodules/fira/ttf/ /Library/Fonts/
open DerZyklop.terminal
