#!/bin/sh

### Set new dotfiles

ln -sf $PWD/.zshrc ~/.zshrc
ln -sf $PWD/.profile ~/.profile

### Show hidden files in finder

defaults write com.apple.finder AppleShowAllFiles TRUE

### Update brew

brew update

### Install zsh

brew install zsh
sudo chsh -s /usr/local/bin/zsh Offline

### Install git

brew install git

#### Setup git-stuff

git config --global color.ui true
git config --global user.name "Nils Neumann"
git config --global user.email mail@der-zyklop.de
git config --global format.pretty oneline

# For more usefull git-stuff see <http://git-scm.com/book/en/Customizing-Git-Git-Configuration>

### Grunt

brew install node
npm install -g grunt-cli
